on:
  workflow_dispatch:
jobs:
  job1:
    steps:
      - name: Write file
        run: |
          echo "Hello World" >> a.txt
  job2:
    needs: job1
    steps:
      - name: Read file
        run: |
          echo "$(<a.txt )"
